spring:
  application:
    name: back
  output:
    ansi:
      enabled: ALWAYS # ?? ?? ? ANSI ??? ?? ???
logging:
  level:
    com:
      back: debug # ???? ?? ??? debug? ??
server:
  port: 8080 # ?? ?? ??