spring:
  profiles:
    active: dev # ?? ???? dev? ??
  application:
    name: back
  output:
    ansi:
      enabled: ALWAYS # ?? ?? ? ANSI ??? ?? ???
  jackson:
    serialization:
      fail-on-empty-beans: false # ? ?? ??? ? ?? ?? ??
logging:
  level:
    com:
      back: debug # ???? ?? ??? debug? ??
server:
  port: 8080 # ?? ?? ??